#-----------
#GITHUB Action
name: My-GitHubActions-Basics

on:
  push:
    branches: 
      - hillel-lesson-18

jobs: 
  my_testing:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: Print Hello Message
        run: echo "Hello World from testing"
        
  
  
  my_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello Message
        run: echo "Hello World from Deploy"
  
